export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';
export const LOADING_PRODUCTS_SUCCESS = 'LOADING_PRODUCTS_SUCCESS';
export const LOADING_PRODUCTS_ERROR = 'LOADING_PRODUCTS_ERROR';

export const GET_DELETE_PRODUCT = 'GET_DELETE_PRODUCT';
export const GET_DELETE_PRODUCT_SUCCESS = 'GET_DELETE_PRODUCT_SUCCESS';
export const GET_DELETE_PRODUCT_ERROR = 'GET_DELETE_PRODUCT_ERROR';

export const GET_EDIT_PRODUCT = 'GET_EDIT_PRODUCT';
export const START_EDITING_PRODUCT = 'START_EDITING_PRODUCT';
export const GET_EDIT_PRODUCT_SUCCESS = 'GET_EDIT_PRODUCT_SUCCESS';
export const GET_EDIT_PRODUCT_ERROR = 'GET_EDIT_PRODUCT_ERROR';

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'